{% set version = "4.89" %}
{% set sha256 = "17688b122b9e0330042625ae6c15c4486699a11e2483e3d0e97ec1642b93d7b2" %}

package:
  name: lsof
  version: {{ version }}

source:
  url: http://http.debian.net/debian/pool/main/l/lsof/lsof_{{ version }}+dfsg.orig.tar.gz
  sha256: {{ sha256 }}
  # Following are Debian patches from
  # http://http.debian.net/debian/pool/main/l/lsof/lsof_4.89+dfsg-0.1.debian.tar.xz
  patches:
    - patches/manpage
    - patches/examples
    - patches/tests
    - patches/obsolete
    - patches/preset-ccdate

build:
  skip: true  # [not linux]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - perl 5.*
  host:

test:
  commands:
    - lsof -v | grep -qF '{{ version }}'
    - lsof .

about:
  home: http://people.freebsd.org/~abe/
  license: BSD-compatible
  license_family: BSD
  summary: LiSt Open Files
  description: |
    The free, open-source, Unix administrative tool lsof (for LiSt Open Files)
    displays information about files open to Unix processes.
  doc_url: https://people.freebsd.org/~abe/

extra:
  recipe-maintainers:
    - keuv-grvl
