{% set version = "4.99.4" %}

package:
  name: lsof
  version: {{ version }}

source:
  url: https://github.com/lsof-org/lsof/archive/{{ version }}.tar.gz
  sha256: 90d02ae35cd14341bfb04ce80e0030767476b0fc414a0acb115d49e79b13d56c

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - perl

test:
  commands:
    - lsof -v 2>&1 | grep -qF '{{ version }}'
    - lsof .

about:
  home: http://people.freebsd.org/~abe/
  license: BSD-compatible
  license_file: COPYING
  summary: LiSt Open Files
  description: |
    The free, open-source, Unix administrative tool lsof (for LiSt Open Files)
    displays information about files open to Unix processes.
  doc_url: https://lsof.readthedocs.io/

extra:
  recipe-maintainers:
    - danielnachun
    - keuv-grvl
