travis:
  secure:
    BINSTAR_TOKEN: YyVKLx6m1zCd9gCoyn6Wpl4uJVZvxMZbrB9YwkemqcidOfb01t7rrl20193e9mHpKfItnxJQRE3WQaDKNwX7MIxP+vm2Kna1O+Uqh8JXtXRVKgmwWMMFxhxYC/37tFdzDuhcMVffI4HtJzK2b/t7QI1SovnjVF/KxICaNX873GO5Ms9It8uPL5aqdUuJz2lyQ15pLfRjnn2u5TD/aPivlHJ1QiebjNwfFwd5BCb49RrY1HbmGbcFPua62x/yxLQmAGmMNJvTN6kPL7Tj6LeAE0T9i/ZbQ05eWiC4KBHKfhDHs5o2HmmzVmbg7NR8ypp+JI+iEqoo8zd4O99/mGYHqJNyd/Tj7vz0Z2bp7Vsln7SmY6gE4qUDF2AkDjHlBeDFVLXo7Qsp51+asvXgz0TQf0xztBHkTaWHjYB04K9IGB/pSuOxcmrOTUJgWms5JPK70czGKEhlOuyNlITFdliMDpCH7S02w69EnM7rJH1QzLIuVgfREcklLEiD3EMFGreDFh1QsB386Sr00V8+yD+ZJg41mNB0C6eeEVfqrOS5Wxk6ONzdUL9Drg7t/3m2el6omuf9ze+52Bub08zcMTLnJvnFTQU/PD58eaWi61E9hwCqTUIFs46FuWf7faBG7jCfsaidns5qmhRTq0ou36ZQzcALZZAE+RDWVqHsxX2oQOc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
